# Generated by Django 3.1.7 on 2021-03-19 07:21

import django.core.validators
from django.db import migrations, models
import main.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210319_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0), main.validators.validate_even_number]),
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator('Email address is not valid')]),
        ),
    ]
